# Generated by Django 3.0.5 on 2020-04-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200406_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='user_last_name',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
