# Generated by Django 3.0.5 on 2020-04-06 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_campaign_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='campaign_id',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='Update',
        ),
    ]
