# Generated by Django 3.0.5 on 2020-04-07 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200407_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='campaign_iage_url',
            new_name='campaign_image_url',
        ),
    ]
