# Generated by Django 3.0.5 on 2020-04-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200407_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='donators',
            field=models.DecimalField(decimal_places=2, max_digits=35),
        ),
    ]
