# Generated by Django 3.0.5 on 2020-04-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200407_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_hearts',
            field=models.DecimalField(decimal_places=2, max_digits=35),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='days_active',
            field=models.DecimalField(decimal_places=2, max_digits=35),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='days_created',
            field=models.DecimalField(decimal_places=2, max_digits=35),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='social_share_total',
            field=models.DecimalField(decimal_places=2, max_digits=35),
        ),
    ]
