from django.db import models
from api.fields import JSONField


# Create your models here.
class Campaign(models.Model):
    campaign_id = models.CharField(max_length=999999999999999999999999999, primary_key=True)
    url = models.TextField()
    auto_fb_post_mode = models.TextField()
    collected_date = models.TextField()
    category_id = models.TextField()
    category = models.TextField()
    currencycode = models.TextField()
    current_amount = models.DecimalField(max_digits=35, decimal_places=2)
    goal = models.DecimalField(max_digits=35, decimal_places=2)
    donators = models.DecimalField(max_digits=35, decimal_places=2)
    days_active = models.DecimalField(max_digits=35, decimal_places=2)
    days_created = models.DecimalField(max_digits=35, decimal_places=2)
    title = models.TextField()
    description = models.TextField()
    default_url = models.TextField()
    has_beneficiary = models.BooleanField()
    media_type = models.TextField()
    project_type = models.TextField()
    turn_off_donations = models.TextField()
    user_id = models.TextField()
    user_first_name = models.TextField()
    user_last_name = models.TextField()
    user_facebook_id = models.TextField()
    user_profile_url = models.TextField()
    visible_in_search = models.TextField()
    status = models.TextField()
    deactivated = models.TextField()
    state = models.TextField()
    is_launched = models.TextField()
    campaign_image_url = models.TextField()
    created_at = models.TextField()
    launch_date = models.TextField()
    campaign_hearts = models.DecimalField(max_digits=35, decimal_places=2)
    social_share_total = models.DecimalField(max_digits=35, decimal_places=2)
    social_share_last_udpate = models.TextField()
    location_city = models.TextField()
    location_country = models.TextField()
    location_zip = models.TextField()
    is_charity = models.TextField()
    charity_valid = models.TextField()
    charity_npo_id = models.TextField()
    charity_name = models.TextField()
    velocity = models.TextField()
    overall_popularity = models.CharField(max_length=999999999999999999999999999)
    percent_goal_complete = models.DecimalField(max_digits=35, decimal_places=10)
    avg_donation_per_donor = models.DecimalField(max_digits=35, decimal_places=10)


# class Donation(models.Model):
#     donation_id = models.CharField(max_length=999999999999999999999999999, primary_key=True)
#     campaign_id = models.ForeignKey(Campaign, on_delete=models.PROTECT)
#     collected_date = models.TextField()
#     amount = models.DecimalField(max_digits=35, decimal_places=2)
#     is_offline = models.TextField()
#     is_anonymous = models.TextField()
#     name = models.TextField()
#     created_at = models.TextField()
#     profile_url = models.TextField()
#     verified = models.TextField()


# class Update(models.Model):
#     update_id = models.CharField(max_length=999999999999999999999999999, primary_key=True)
#     campaign_id = models.ForeignKey(Campaign, on_delete=models.PROTECT)
#     collected_date = models.TextField()
#     photo_url = models.TextField()
#     created_at = models.TextField()
#     updates_author = models.TextField()
#     updates_author_type = models.TextField()
#     updates_text = models.TextField()
#     comments = models.TextField()